// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SCMS.Infrastructure.Persistence;

#nullable disable

namespace SCMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518120000_AddClubGroupInfo")]
    public partial class AddClubGroupInfo
    {
    }
}
